// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/merchant/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_proto_merchant_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *GetMerchantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Error         bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional: why error happened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_proto_merchant_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *GetMerchantResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMerchantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMerchantResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetMerchantResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetMerchantResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *GetMerchantResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetItemsDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ItemIds       []int64                `protobuf:"varint,2,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"` // Array of item IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsDetailRequest) Reset() {
	*x = GetItemsDetailRequest{}
	mi := &file_proto_merchant_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsDetailRequest) ProtoMessage() {}

func (x *GetItemsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsDetailRequest.ProtoReflect.Descriptor instead.
func (*GetItemsDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsDetailRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetItemsDetailRequest) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type ItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Error         bool                   `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Optional: why error happened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_proto_merchant_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_proto_merchant_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *ItemDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemDetail) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemDetail) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ItemDetail) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetItemsDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Items         []*ItemDetail          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // Array of item details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsDetailResponse) Reset() {
	*x = GetItemsDetailResponse{}
	mi := &file_proto_merchant_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsDetailResponse) ProtoMessage() {}

func (x *GetItemsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsDetailResponse.ProtoReflect.Descriptor instead.
func (*GetItemsDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsDetailResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *GetItemsDetailResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetItemsDetailResponse) GetItems() []*ItemDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_merchant_merchant_proto protoreflect.FileDescriptor

const file_proto_merchant_merchant_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/merchant/merchant.proto\x12\bmerchant\"$\n" +
	"\x12GetMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xae\x01\n" +
	"\x13GetMerchantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"S\n" +
	"\x15GetItemsDetailRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x03R\n" +
	"merchantId\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\x03R\aitemIds\"\x81\x01\n" +
	"\n" +
	"ItemDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05error\x18\x04 \x01(\bR\x05error\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x7f\n" +
	"\x16GetItemsDetailResponse\x12\x14\n" +
	"\x05error\x18\x03 \x01(\bR\x05error\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.merchant.ItemDetailR\x05items2\xb2\x01\n" +
	"\x0fMerchantService\x12J\n" +
	"\vGetMerchant\x12\x1c.merchant.GetMerchantRequest\x1a\x1d.merchant.GetMerchantResponse\x12S\n" +
	"\x0eGetItemsDetail\x12\x1f.merchant.GetItemsDetailRequest\x1a .merchant.GetItemsDetailResponseB2Z0github.com/sabiqazhar/belimang-go/proto/merchantb\x06proto3"

var (
	file_proto_merchant_merchant_proto_rawDescOnce sync.Once
	file_proto_merchant_merchant_proto_rawDescData []byte
)

func file_proto_merchant_merchant_proto_rawDescGZIP() []byte {
	file_proto_merchant_merchant_proto_rawDescOnce.Do(func() {
		file_proto_merchant_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merchant_merchant_proto_rawDesc), len(file_proto_merchant_merchant_proto_rawDesc)))
	})
	return file_proto_merchant_merchant_proto_rawDescData
}

var file_proto_merchant_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_merchant_merchant_proto_goTypes = []any{
	(*GetMerchantRequest)(nil),     // 0: merchant.GetMerchantRequest
	(*GetMerchantResponse)(nil),    // 1: merchant.GetMerchantResponse
	(*GetItemsDetailRequest)(nil),  // 2: merchant.GetItemsDetailRequest
	(*ItemDetail)(nil),             // 3: merchant.ItemDetail
	(*GetItemsDetailResponse)(nil), // 4: merchant.GetItemsDetailResponse
}
var file_proto_merchant_merchant_proto_depIdxs = []int32{
	3, // 0: merchant.GetItemsDetailResponse.items:type_name -> merchant.ItemDetail
	0, // 1: merchant.MerchantService.GetMerchant:input_type -> merchant.GetMerchantRequest
	2, // 2: merchant.MerchantService.GetItemsDetail:input_type -> merchant.GetItemsDetailRequest
	1, // 3: merchant.MerchantService.GetMerchant:output_type -> merchant.GetMerchantResponse
	4, // 4: merchant.MerchantService.GetItemsDetail:output_type -> merchant.GetItemsDetailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_merchant_merchant_proto_init() }
func file_proto_merchant_merchant_proto_init() {
	if File_proto_merchant_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merchant_merchant_proto_rawDesc), len(file_proto_merchant_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merchant_merchant_proto_goTypes,
		DependencyIndexes: file_proto_merchant_merchant_proto_depIdxs,
		MessageInfos:      file_proto_merchant_merchant_proto_msgTypes,
	}.Build()
	File_proto_merchant_merchant_proto = out.File
	file_proto_merchant_merchant_proto_goTypes = nil
	file_proto_merchant_merchant_proto_depIdxs = nil
}
