// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Users struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	IsAdmin   pgtype.Bool      `json:"is_admin"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
