// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Merchants struct {
	ID               int64            `json:"id"`
	Name             string           `json:"name"`
	MerchantCategory string           `json:"merchant_category"`
	ImageUrl         string           `json:"image_url"`
	Longitude        float64          `json:"longitude"`
	Latitude         float64          `json:"latitude"`
	H3Index          pgtype.Int8      `json:"h3_index"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}
