// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchants, error)
}

var _ Querier = (*Queries)(nil)
