// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (id, name, merchant_category, image_url, longitude, latitude, h3_index)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, merchant_category, image_url, longitude, latitude, h3_index, created_at
`

type CreateMerchantParams struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	MerchantCategory string      `json:"merchant_category"`
	ImageUrl         string      `json:"image_url"`
	Longitude        float64     `json:"longitude"`
	Latitude         float64     `json:"latitude"`
	H3Index          pgtype.Int8 `json:"h3_index"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchants, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.MerchantCategory,
		arg.ImageUrl,
		arg.Longitude,
		arg.Latitude,
		arg.H3Index,
	)
	var i Merchants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantCategory,
		&i.ImageUrl,
		&i.Longitude,
		&i.Latitude,
		&i.H3Index,
		&i.CreatedAt,
	)
	return i, err
}
