// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// noinspection SqlResolve FOR WHOLE FILE
	// noinspection SqlNoDataSourceInspection
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchants, error)
	GetMerchantList(ctx context.Context, arg GetMerchantListParams) ([]Merchants, error)
}

var _ Querier = (*Queries)(nil)
