// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItem = `-- name: AddItem :one
INSERT INTO items (id, merchant_id, name, price, image_url, product_category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type AddItemParams struct {
	ID              int64          `json:"id"`
	MerchantID      pgtype.Int8    `json:"merchant_id"`
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	ImageUrl        string         `json:"image_url"`
	ProductCategory string         `json:"product_category"`
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, addItem,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Price,
		arg.ImageUrl,
		arg.ProductCategory,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMerchant = `-- name: CreateMerchant :one

INSERT INTO merchants (id, name, merchant_category, image_url, longitude, latitude, h3_index)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, merchant_category, image_url, longitude, latitude, h3_index, created_at
`

type CreateMerchantParams struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	MerchantCategory string      `json:"merchant_category"`
	ImageUrl         string      `json:"image_url"`
	Longitude        float64     `json:"longitude"`
	Latitude         float64     `json:"latitude"`
	H3Index          pgtype.Int8 `json:"h3_index"`
}

// noinspection SqlResolve FOR WHOLE FILE
// noinspection SqlNoDataSourceInspection
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchants, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.MerchantCategory,
		arg.ImageUrl,
		arg.Longitude,
		arg.Latitude,
		arg.H3Index,
	)
	var i Merchants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantCategory,
		&i.ImageUrl,
		&i.Longitude,
		&i.Latitude,
		&i.H3Index,
		&i.CreatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, price, product_category, image_url, merchant_id  FROM items WHERE id = $1
`

type GetItemByIDRow struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Price           pgtype.Numeric `json:"price"`
	ProductCategory string         `json:"product_category"`
	ImageUrl        string         `json:"image_url"`
	MerchantID      pgtype.Int8    `json:"merchant_id"`
}

func (q *Queries) GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.ProductCategory,
		&i.ImageUrl,
		&i.MerchantID,
	)
	return i, err
}

const getItemList = `-- name: GetItemList :many
SELECT id, name, product_category, price, image_url, created_at
FROM items
WHERE
        ($1::bigint IS NULL OR id = $1::bigint)
    AND
        ($2::text IS NULL OR LOWER(name) ILIKE LOWER($2::text))
    AND
        ($3::text IS NULL OR product_category = $3::text)
ORDER BY
    CASE
        WHEN $4::boolean = true THEN created_at
        END ASC,
    CASE
        WHEN $5::boolean = true THEN created_at
        END DESC,
    CASE
        WHEN $4::boolean = false AND $5::boolean = false THEN created_at
        END DESC
LIMIT $7::int
    OFFSET $6::int
`

type GetItemListParams struct {
	ItemId          pgtype.Int8 `json:"itemId"`
	Name            pgtype.Text `json:"name"`
	ProductCategory pgtype.Text `json:"product_category"`
	SortAsc         bool        `json:"sort_asc"`
	SortDesc        bool        `json:"sort_desc"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

type GetItemListRow struct {
	ID              int64            `json:"id"`
	Name            string           `json:"name"`
	ProductCategory string           `json:"product_category"`
	Price           pgtype.Numeric   `json:"price"`
	ImageUrl        string           `json:"image_url"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetItemList(ctx context.Context, arg GetItemListParams) ([]GetItemListRow, error) {
	rows, err := q.db.Query(ctx, getItemList,
		arg.ItemId,
		arg.Name,
		arg.ProductCategory,
		arg.SortAsc,
		arg.SortDesc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemListRow
	for rows.Next() {
		var i GetItemListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProductCategory,
			&i.Price,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantById = `-- name: GetMerchantById :one
SELECT id, name, longitude, latitude FROM merchants WHERE id = $1
`

type GetMerchantByIdRow struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
}

func (q *Queries) GetMerchantById(ctx context.Context, id int64) (GetMerchantByIdRow, error) {
	row := q.db.QueryRow(ctx, getMerchantById, id)
	var i GetMerchantByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getMerchantList = `-- name: GetMerchantList :many
SELECT
    id,
    name,
    merchant_category,
    image_url,
    latitude,
    longitude,
    created_at
FROM merchants
WHERE
  -- Filter by merchantId (optional)
    ($1::bigint IS NULL OR id = $1::bigint)

  -- Filter by name with wildcard, case insensitive (optional)
  AND ($2::text IS NULL OR LOWER(name) ILIKE LOWER($2::text))

  -- Filter by category (optional)
  AND ($3::text IS NULL OR merchant_category = $3::text)

ORDER BY
    -- Dynamic sorting
    CASE
        WHEN $4::boolean = true THEN created_at
        END ASC,
    CASE
        WHEN $5::boolean = true THEN created_at
        END DESC,
    -- Default sort if neither asc nor desc
    CASE
        WHEN $4::boolean = false AND $5::boolean = false THEN created_at
        END DESC

LIMIT $7::int
    OFFSET $6::int
`

type GetMerchantListParams struct {
	MerchantID       pgtype.Int8 `json:"merchant_id"`
	Name             pgtype.Text `json:"name"`
	MerchantCategory pgtype.Text `json:"merchant_category"`
	SortAsc          bool        `json:"sort_asc"`
	SortDesc         bool        `json:"sort_desc"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

type GetMerchantListRow struct {
	ID               int64            `json:"id"`
	Name             string           `json:"name"`
	MerchantCategory string           `json:"merchant_category"`
	ImageUrl         string           `json:"image_url"`
	Latitude         float64          `json:"latitude"`
	Longitude        float64          `json:"longitude"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMerchantList(ctx context.Context, arg GetMerchantListParams) ([]GetMerchantListRow, error) {
	rows, err := q.db.Query(ctx, getMerchantList,
		arg.MerchantID,
		arg.Name,
		arg.MerchantCategory,
		arg.SortAsc,
		arg.SortDesc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantListRow
	for rows.Next() {
		var i GetMerchantListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantCategory,
			&i.ImageUrl,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
