// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddItem(ctx context.Context, arg AddItemParams) (int64, error)
	// noinspection SqlResolve FOR WHOLE FILE
	// noinspection SqlNoDataSourceInspection
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchants, error)
	GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error)
	GetItemList(ctx context.Context, arg GetItemListParams) ([]GetItemListRow, error)
	GetMerchantById(ctx context.Context, id int64) (GetMerchantByIdRow, error)
	GetMerchantList(ctx context.Context, arg GetMerchantListParams) ([]GetMerchantListRow, error)
}

var _ Querier = (*Queries)(nil)
