// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Images struct {
	ID        int64            `json:"id"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	UploadBy  pgtype.Int8      `json:"upload_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
