// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertImage(ctx context.Context, arg InsertImageParams) (Images, error)
}

var _ Querier = (*Queries)(nil)
