// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertImage = `-- name: InsertImage :one
INSERT INTO images (
    id,
    image_url,
    upload_by
) VALUES (
    $1, $2, $3
)
RETURNING id, image_url, upload_by, created_at
`

type InsertImageParams struct {
	ID       int64       `json:"id"`
	ImageUrl pgtype.Text `json:"image_url"`
	UploadBy pgtype.Int8 `json:"upload_by"`
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Images, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.ID, arg.ImageUrl, arg.UploadBy)
	var i Images
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.UploadBy,
		&i.CreatedAt,
	)
	return i, err
}
