// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertOrderItems implements pgx.CopyFromSource.
type iteratorForInsertOrderItems struct {
	rows                 []InsertOrderItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertOrderItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertOrderItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MerchantID,
		r.rows[0].OrderID,
		r.rows[0].ProductID,
		r.rows[0].Quantity,
		r.rows[0].Price,
		r.rows[0].StartingPoint,
	}, nil
}

func (r iteratorForInsertOrderItems) Err() error {
	return nil
}

func (q *Queries) InsertOrderItems(ctx context.Context, arg []InsertOrderItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_items"}, []string{"id", "merchant_id", "order_id", "product_id", "quantity", "price", "starting_point"}, &iteratorForInsertOrderItems{rows: arg})
}
