// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderItems struct {
	ID            int64          `json:"id"`
	MerchantID    string         `json:"merchant_id"`
	OrderID       pgtype.Int8    `json:"order_id"`
	ProductID     string         `json:"product_id"`
	Quantity      int32          `json:"quantity"`
	Price         pgtype.Numeric `json:"price"`
	StartingPoint pgtype.Bool    `json:"starting_point"`
}

type Orders struct {
	ID                             int64            `json:"id"`
	CustomerID                     int32            `json:"customer_id"`
	OrderDate                      pgtype.Timestamp `json:"order_date"`
	Status                         string           `json:"status"`
	TotalAmount                    pgtype.Numeric   `json:"total_amount"`
	EstimatedDeliveryTimeInMinutes int32            `json:"estimated_delivery_time_in_minutes"`
	TotalDistanceInMeters          int32            `json:"total_distance_in_meters"`
	Longitude                      pgtype.Float8    `json:"longitude"`
	Latitude                       pgtype.Float8    `json:"latitude"`
}
