// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error)
	InsertOrderItems(ctx context.Context, arg []InsertOrderItemsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
