// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (id, customer_id, order_date, status, total_amount, estimated_delivery_time_in_minutes)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type InsertOrderParams struct {
	ID                             int64            `json:"id"`
	CustomerID                     int32            `json:"customer_id"`
	OrderDate                      pgtype.Timestamp `json:"order_date"`
	Status                         string           `json:"status"`
	TotalAmount                    pgtype.Numeric   `json:"total_amount"`
	EstimatedDeliveryTimeInMinutes int32            `json:"estimated_delivery_time_in_minutes"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.CustomerID,
		arg.OrderDate,
		arg.Status,
		arg.TotalAmount,
		arg.EstimatedDeliveryTimeInMinutes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type InsertOrderItemsParams struct {
	ID            int64          `json:"id"`
	MerchantID    int64          `json:"merchant_id"`
	OrderID       pgtype.Int8    `json:"order_id"`
	ProductID     int32          `json:"product_id"`
	Quantity      int32          `json:"quantity"`
	Price         pgtype.Numeric `json:"price"`
	StartingPoint pgtype.Bool    `json:"starting_point"`
}
