// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderById = `-- name: GetOrderById :one
SELECT id, customer_id, order_date, status, total_amount, estimated_delivery_time_in_minutes, longitude, latitude, total_distance_in_meters
FROM orders
WHERE id = $1
`

type GetOrderByIdRow struct {
	ID                             int64            `json:"id"`
	CustomerID                     int32            `json:"customer_id"`
	OrderDate                      pgtype.Timestamp `json:"order_date"`
	Status                         string           `json:"status"`
	TotalAmount                    pgtype.Numeric   `json:"total_amount"`
	EstimatedDeliveryTimeInMinutes int32            `json:"estimated_delivery_time_in_minutes"`
	Longitude                      pgtype.Float8    `json:"longitude"`
	Latitude                       pgtype.Float8    `json:"latitude"`
	TotalDistanceInMeters          int32            `json:"total_distance_in_meters"`
}

func (q *Queries) GetOrderById(ctx context.Context, id int64) (GetOrderByIdRow, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i GetOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrderDate,
		&i.Status,
		&i.TotalAmount,
		&i.EstimatedDeliveryTimeInMinutes,
		&i.Longitude,
		&i.Latitude,
		&i.TotalDistanceInMeters,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (id, customer_id, order_date, status, total_amount, estimated_delivery_time_in_minutes, longitude, latitude, total_distance_in_meters)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id
`

type InsertOrderParams struct {
	ID                             int64            `json:"id"`
	CustomerID                     int32            `json:"customer_id"`
	OrderDate                      pgtype.Timestamp `json:"order_date"`
	Status                         string           `json:"status"`
	TotalAmount                    pgtype.Numeric   `json:"total_amount"`
	EstimatedDeliveryTimeInMinutes int32            `json:"estimated_delivery_time_in_minutes"`
	Longitude                      pgtype.Float8    `json:"longitude"`
	Latitude                       pgtype.Float8    `json:"latitude"`
	TotalDistanceInMeters          int32            `json:"total_distance_in_meters"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.CustomerID,
		arg.OrderDate,
		arg.Status,
		arg.TotalAmount,
		arg.EstimatedDeliveryTimeInMinutes,
		arg.Longitude,
		arg.Latitude,
		arg.TotalDistanceInMeters,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type InsertOrderItemsParams struct {
	ID            int64          `json:"id"`
	MerchantID    string         `json:"merchant_id"`
	OrderID       pgtype.Int8    `json:"order_id"`
	ProductID     string         `json:"product_id"`
	Quantity      int32          `json:"quantity"`
	Price         pgtype.Numeric `json:"price"`
	StartingPoint pgtype.Bool    `json:"starting_point"`
}

const updateOrderAmount = `-- name: UpdateOrderAmount :exec
UPDATE orders SET total_amount = $2 WHERE id = $1
`

type UpdateOrderAmountParams struct {
	ID          int64          `json:"id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateOrderAmount(ctx context.Context, arg UpdateOrderAmountParams) error {
	_, err := q.db.Exec(ctx, updateOrderAmount, arg.ID, arg.TotalAmount)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
